[package]
name = "hopper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
project-root = "0.2.2"
serde = "1.0.152"
serde_derive = "1.0.152"
tempfile = "3.3.0"
toml = "0.5.10"
libsqlite3-sys = "0.25.2"
rusqlite = { version = "0.28.0", features = ["bundled"] }
press-btn-continue = "0.1.1"
