[package]
name = "bhop"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
serde = "1.0.152"
serde_derive = "1.0.152"
tempfile = "3.3.0"
toml = "0.5.10"
press-btn-continue = "0.1.1"
chrono = "0.4.23"
anyhow = "1.0"
sqlite = "0.30.4"
colored = "2.0.0"
